/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pkl_certs_NativeCertificateLoader */

#ifndef _Included_org_pkl_certs_NativeCertificateLoader
#define _Included_org_pkl_certs_NativeCertificateLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pkl_certs_NativeCertificateLoader
 * Method:    getBytes
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_pkl_certs_NativeCertificateLoader_getBytes(
		JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
